-- PUR-02: purchase orders and goods receipt.
--
-- Three tables, not two. `purchase_order_receipts` exists because a PO is
-- received in EVENTS, not as a running total: partial receipt is the normal
-- case, and idempotency has to key off the individual delivery. Storing only
-- `quantity_received` on the line would make a replayed receipt indistinguishable
-- from a real second delivery of the same quantity.
--
-- Cost basis is per-receipt MOVING AVERAGE, decided before this migration was
-- written -- see docs/reference/decision-cost-basis.md for the rationale and
-- the edge cases. This is the first real cost data in the system.

begin;

create type public.purchase_order_status as enum ('draft', 'sent', 'partial', 'received', 'cancelled');

create table public.purchase_orders (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  supplier_id uuid not null references public.suppliers(id) on delete restrict,
  -- Human-facing reference, unique per tenant. Generated by the route.
  po_number text not null,
  status public.purchase_order_status not null default 'draft',
  expected_date date,
  notes text,
  created_by uuid references public.staff_members(id),
  created_at timestamptz not null default now(),
  unique (tenant_id, po_number)
);

create index idx_purchase_orders_tenant_id on public.purchase_orders(tenant_id);
create index idx_purchase_orders_supplier_id on public.purchase_orders(supplier_id);
-- Supports the on_order lookup the reorder heuristic runs per variant.
create index idx_purchase_orders_status on public.purchase_orders(tenant_id, status);

create table public.purchase_order_lines (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  purchase_order_id uuid not null references public.purchase_orders(id) on delete cascade,
  variant_id uuid not null references public.variants(id) on delete restrict,
  quantity_ordered integer not null check (quantity_ordered > 0),
  -- Derived: maintained by the receipt trigger below, never written by the app.
  quantity_received integer not null default 0 check (quantity_received >= 0),
  unit_cost numeric(10, 2) not null check (unit_cost >= 0),
  created_at timestamptz not null default now(),
  -- One line per variant per PO, so quantity_received is unambiguous.
  unique (purchase_order_id, variant_id)
);

create index idx_purchase_order_lines_po_id on public.purchase_order_lines(purchase_order_id);
create index idx_purchase_order_lines_tenant_id on public.purchase_order_lines(tenant_id);
create index idx_purchase_order_lines_variant_id on public.purchase_order_lines(variant_id);

-- One row per delivery event against a PO.
create table public.purchase_order_receipts (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  purchase_order_id uuid not null references public.purchase_orders(id) on delete cascade,
  -- Client-supplied idempotency key, same pattern and reasoning as 0018's
  -- (tenant_id, client_sale_id): the guarantee is the unique index, not the
  -- route's check-then-insert, which races under concurrent retries.
  client_receipt_id uuid not null,
  received_at timestamptz not null default now(),
  created_by uuid references public.staff_members(id),
  note text
);

create unique index idx_po_receipts_tenant_client_receipt_id
  on public.purchase_order_receipts (tenant_id, client_receipt_id);

comment on index public.idx_po_receipts_tenant_client_receipt_id is
  'PUR-02: guarantees a retried goods receipt records exactly once per tenant. Receiving twice must not double stock.';

create index idx_po_receipts_po_id on public.purchase_order_receipts(purchase_order_id);

create table public.purchase_order_receipt_lines (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  receipt_id uuid not null references public.purchase_order_receipts(id) on delete cascade,
  purchase_order_line_id uuid not null references public.purchase_order_lines(id) on delete restrict,
  variant_id uuid not null references public.variants(id) on delete restrict,
  quantity_received integer not null check (quantity_received > 0),
  -- Cost is captured per receipt, not per line: the same variant can arrive at
  -- a different price on a later delivery, and the moving average needs the
  -- price that THIS delivery actually charged.
  unit_cost numeric(10, 2) not null check (unit_cost >= 0),
  created_at timestamptz not null default now(),
  unique (receipt_id, purchase_order_line_id)
);

create index idx_po_receipt_lines_receipt_id on public.purchase_order_receipt_lines(receipt_id);
create index idx_po_receipt_lines_tenant_id on public.purchase_order_receipt_lines(tenant_id);

-- Moving-average cost per variant. Null until the variant's first receipt --
-- callers must report margin as unavailable rather than assuming zero cost.
alter table public.variants add column moving_average_cost numeric(10, 2);

comment on column public.variants.moving_average_cost is
  'Per-receipt moving average unit cost. Null until first goods receipt. See docs/reference/decision-cost-basis.md.';

-- ---------------------------------------------------------------------------
-- Receipt application. Everything that must happen together happens here, in
-- one AFTER INSERT trigger, so ordering cannot be got wrong by a caller:
--   1. moving average, computed from stock BEFORE this receipt is applied
--   2. the receive stock movement (which is what actually moves stock, via
--      0008/0019's own apply_stock_movement trigger)
--   3. the line's running quantity_received
--   4. the PO's derived status
-- Step 1 strictly precedes step 2 -- the average weights against prior stock,
-- so reading the level after the movement landed would double-count this
-- delivery.
create or replace function public.apply_purchase_receipt_line() returns trigger as $$
declare
  stock_before integer;
  average_before numeric(10, 2);
  po_id uuid;
  total_ordered integer;
  total_received integer;
begin
  select coalesce(vsl.quantity, 0), v.moving_average_cost
    into stock_before, average_before
  from public.variants v
  left join public.variant_stock_levels vsl on vsl.variant_id = v.id
  where v.id = new.variant_id;

  -- Weighted average only makes sense against real prior stock. With no prior
  -- stock, no prior average, or an oversold (<= 0) balance, this delivery's
  -- price IS the cost -- see decision-cost-basis.md "Edge cases".
  if stock_before > 0 and average_before is not null then
    update public.variants
      set moving_average_cost = round(
        ((stock_before * average_before) + (new.quantity_received * new.unit_cost))
        / (stock_before + new.quantity_received), 2)
      where id = new.variant_id;
  else
    update public.variants set moving_average_cost = new.unit_cost where id = new.variant_id;
  end if;

  insert into public.stock_movements (tenant_id, variant_id, movement_type, quantity_delta, reference_id)
  values (new.tenant_id, new.variant_id, 'receive', new.quantity_received, new.receipt_id);

  update public.purchase_order_lines
    set quantity_received = quantity_received + new.quantity_received
    where id = new.purchase_order_line_id
    returning purchase_order_id into po_id;

  -- Derived status. Over-receipt is ALLOWED (the goods physically arrived) but
  -- is not silently swallowed: the route flags it to the caller, and a line
  -- whose received exceeds ordered still counts as fully received here.
  select sum(quantity_ordered), sum(quantity_received)
    into total_ordered, total_received
  from public.purchase_order_lines where purchase_order_id = po_id;

  update public.purchase_orders
    set status = case
      when total_received >= total_ordered then 'received'::public.purchase_order_status
      else 'partial'::public.purchase_order_status
    end
    where id = po_id and status <> 'cancelled';

  return new;
end;
$$ language plpgsql security definer set search_path = public;

create trigger trg_apply_purchase_receipt_line
  after insert on public.purchase_order_receipt_lines
  for each row execute function public.apply_purchase_receipt_line();

-- ---------------------------------------------------------------------------
-- RLS. Same tenant-isolation shape as every other table.

alter table public.purchase_orders enable row level security;
alter table public.purchase_order_lines enable row level security;
alter table public.purchase_order_receipts enable row level security;
alter table public.purchase_order_receipt_lines enable row level security;

create policy tenant_isolation_purchase_orders on public.purchase_orders
  for all
  using (tenant_id = current_setting('app.tenant_id', true)::uuid)
  with check (tenant_id = current_setting('app.tenant_id', true)::uuid);

create policy tenant_isolation_purchase_order_lines on public.purchase_order_lines
  for all
  using (tenant_id = current_setting('app.tenant_id', true)::uuid)
  with check (tenant_id = current_setting('app.tenant_id', true)::uuid);

create policy tenant_isolation_po_receipts on public.purchase_order_receipts
  for all
  using (tenant_id = current_setting('app.tenant_id', true)::uuid)
  with check (tenant_id = current_setting('app.tenant_id', true)::uuid);

create policy tenant_isolation_po_receipt_lines on public.purchase_order_receipt_lines
  for all
  using (tenant_id = current_setting('app.tenant_id', true)::uuid)
  with check (tenant_id = current_setting('app.tenant_id', true)::uuid);

grant select, insert, update on public.purchase_orders to app_runtime;
grant select, insert, update on public.purchase_order_lines to app_runtime;
-- Receipts are append-only history of what physically arrived: no update, no
-- delete. A wrong receipt is corrected by a compensating adjustment movement,
-- exactly as 0007 does for the stock ledger.
grant select, insert on public.purchase_order_receipts to app_runtime;
grant select, insert on public.purchase_order_receipt_lines to app_runtime;

commit;
