-- Products & Variants (CATALOG-01/CATALOG-02).
-- D-01: fixed size/color/material axes on variants directly — no EAV/JSONB attribute table.
-- D-02: every product has >=1 variant; stock always attaches to variant_id, never product_id.
-- D-03: sku is auto-generated by the app at creation time, owner-overridable, unique per tenant.
-- D-04: identity_locked flips true (via 0008's trigger) the first time any stock_movements row
-- references this variant; a BEFORE UPDATE trigger (0008) then blocks further size/color/material edits.

create table public.products (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  name text not null,
  category text,
  created_at timestamptz not null default now()
);

create table public.variants (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  product_id uuid not null references public.products(id) on delete cascade,
  sku text not null,
  size text,
  color text,
  material text,
  price numeric(10,2) not null,
  -- D-11: nonzero default so a forgotten threshold doesn't silently disable alerts (RESEARCH.md Pitfall 5).
  reorder_threshold integer not null default 4,
  identity_locked boolean not null default false,
  created_at timestamptz not null default now(),
  unique (tenant_id, sku)
);

create index idx_products_tenant_id on public.products(tenant_id);
create index idx_variants_tenant_id on public.variants(tenant_id);
create index idx_variants_product_id on public.variants(product_id);

alter table public.products enable row level security;
alter table public.variants enable row level security;

create policy tenant_isolation_products on public.products
  for all
  using (tenant_id = current_setting('app.tenant_id', true)::uuid)
  with check (tenant_id = current_setting('app.tenant_id', true)::uuid);

create policy tenant_isolation_variants on public.variants
  for all
  using (tenant_id = current_setting('app.tenant_id', true)::uuid)
  with check (tenant_id = current_setting('app.tenant_id', true)::uuid);

grant select, insert, update, delete on public.products, public.variants to app_runtime;
-- Phase 3+ tenant-owned tables must repeat this grant reminder in their own migration.
